# Local PostgreSQL Database Configuration
# 本地开发环境数据库配置

database:
  host: "localhost"
  port: 5432
  database: "hya_ocr_local"
  username: "hya_ocr_user"
  password: "local_dev_password"  # 本地开发密码
  
  # Connection pool settings
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600
  
  # Development-specific settings
  echo: true  # Enable SQL logging in development
  echo_pool: false
  
  # SSL settings (disabled for local)
  ssl_mode: "disable"
  
  # Connection options
  options:
    client_encoding: "utf8"
    timezone: "Asia/Singapore"
    
# Environment-specific settings
environment:
  name: "local"
  debug: true
  log_level: "DEBUG"
  
# Features enabled in local environment
features:
  auto_migrate: true  # Automatically run migrations
  seed_data: true     # Load sample data
  reset_on_start: false  # Don't reset DB on every start
  
# Backup settings (minimal for local)
backup:
  enabled: false
  
# Monitoring settings
monitoring:
  enabled: false
  slow_query_threshold: 1.0  # Log queries slower than 1 second
  
# Additional local development settings
development:
  create_db_if_not_exists: true
  drop_db_on_reset: true
  fixture_data_path: "./fixtures/local"
  
# Connection string template
connection_string: "postgresql://{username}:{password}@{host}:{port}/{database}"