# UAT AWS Aurora PostgreSQL Database Configuration
# UAT环境数据库配置 - 用于用户验收测试

database:
  # Aurora cluster endpoints (populated by Terraform)
  host: "${AURORA_WRITER_ENDPOINT}"
  readonly_host: "${AURORA_READER_ENDPOINT}"
  port: 5432
  database: "hya_ocr"
  username: "${DATABASE_USERNAME}"
  password: "${DATABASE_PASSWORD}"
  
  # Connection pool settings optimized for UAT load
  pool_size: 15
  max_overflow: 30
  pool_timeout: 30
  pool_recycle: 7200  # 2 hours
  pool_pre_ping: true
  
  # UAT settings
  echo: false
  echo_pool: false
  
  # SSL settings (required for Aurora)
  ssl_mode: "require"
  ssl_ca_cert_path: "/opt/rds-ca-2019-root.pem"
  
  # Connection options
  options:
    client_encoding: "utf8"
    timezone: "Asia/Singapore"
    application_name: "gemini-ocr-uat"
    
# Environment-specific settings
environment:
  name: "uat"
  debug: false
  log_level: "INFO"
  
# Features enabled in UAT environment
features:
  auto_migrate: true
  seed_data: false
  reset_on_start: false
  read_replica: true
  performance_insights: true
  
# Backup settings
backup:
  enabled: true
  retention_days: 14
  point_in_time_recovery: true
  
# Monitoring settings
monitoring:
  enabled: true
  slow_query_threshold: 1.5  # Log queries slower than 1.5 seconds
  connection_monitoring: true
  performance_insights: true
  
# AWS-specific settings
aws:
  region: "ap-southeast-1"
  secrets_manager:
    enabled: true
    secret_arn: "${DATABASE_SECRET_ARN}"
  cloudwatch:
    enabled: true
    log_group: "/aws/rds/cluster/uat-hya-ocr-aurora-postgresql/postgresql"
  parameter_store:
    enabled: true
    prefix: "/hya-ocr/uat/database/"
    
# High availability settings
ha:
  connection_retry_attempts: 5
  connection_retry_delay: 2
  failover_timeout: 30
  health_check_interval: 30
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 60
  
# Performance settings
performance:
  statement_timeout: 60000  # 60 seconds
  idle_in_transaction_session_timeout: 600000  # 10 minutes
  max_connections_per_instance: 150
  connection_lifetime: 3600  # 1 hour
  
# Security settings
security:
  require_ssl: true
  verify_ssl_cert: true
  allowed_hosts:
    - "*.ap-southeast-1.rds.amazonaws.com"
  encrypt_credentials: true
  
# Load balancing for read operations
load_balancing:
  read_write_split: true
  read_weight: 70  # 70% read, 30% write
  sticky_sessions: false
  
# Caching settings
cache:
  query_cache_enabled: true
  cache_ttl: 300  # 5 minutes
  max_cache_size: "128MB"
  
# Connection string templates
connection_string: "postgresql://{username}:{password}@{host}:{port}/{database}?sslmode={ssl_mode}&application_name={application_name}&statement_timeout={statement_timeout}"
readonly_connection_string: "postgresql://{username}:{password}@{readonly_host}:{port}/{database}?sslmode={ssl_mode}&application_name={application_name}-readonly"