"""Make prompt_path and schema_path nullable

Revision ID: make_paths_nullable
Revises: 57b129edcc85
Create Date: 2025-09-16 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b001_make_paths_nullable'
down_revision = '57b129edcc85'
branch_labels = None
depends_on = None


def upgrade():
    """Make prompt_path and schema_path nullable to support new config workflow"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_document_configs', 'prompt_path',
                    existing_type=sa.VARCHAR(length=500),
                    nullable=True)
    op.alter_column('company_document_configs', 'schema_path',
                    existing_type=sa.VARCHAR(length=500),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    """Revert prompt_path and schema_path to be non-nullable"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_document_configs', 'prompt_path',
                    existing_type=sa.VARCHAR(length=500),
                    nullable=False)
    op.alter_column('company_document_configs', 'schema_path',
                    existing_type=sa.VARCHAR(length=500),
                    nullable=False)
    # ### end Alembic commands ###